version: "3.9"
volumes:
  pg_snippets_local: {}
services:
  pg-snippets:
    image: postgres:16
    environment:
      POSTGRES_USER: snippets
      POSTGRES_PASSWORD: snippets
      POSTGRES_DB: snippets
    ports: ["5433:5432"]
    volumes: [ "pg_snippets_local:/var/lib/postgresql/data" ]
    networks:
      printscript-dev:
        aliases: [ pg-snippets ]
    profiles: [ "local" ]

  snippets:
    build: .
    container_name: ps-snippets-local
    environment:
      SERVER_PORT: 8080
      LOGGING_LEVEL_ROOT: DEBUG
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg-snippets:5432/snippets
      SPRING_DATASOURCE_USERNAME: snippets
      SPRING_DATASOURCE_PASSWORD: snippets
      EXECUTION_BASE_URL: http://execution:8080
    depends_on: [ pg-snippets ]
    ports: ["8082:8080"]
    networks:
      printscript-dev:
        aliases: [ snippets ]
    profiles: [ "local" ]
networks:
  printscript-dev:
    external: true
