version: "3.9"
services:
  pg-tests:
    image: postgres:16
    environment:
      POSTGRES_USER: tests
      POSTGRES_PASSWORD: tests
      POSTGRES_DB: tests
    ports: [ "5434:5432" ]
    volumes:
      - pg_tests:/var/lib/postgresql/data

volumes:
  pg_tests: